### ISSUE TITLE
MediaDescription: Lacking test  for multiple fmt in one media description

### ISSUE THREAD

**Issue by teeson** [gortc/sdp#10]
According to RFC4566, the following SDP is allowed:

> Up to one rtpmap attribute can be defined for each media format
> specified.  Thus, we might have the following:

```
m=audio 49230 RTP/AVP 96 97 98
a=rtpmap:96 L8/8000
a=rtpmap:97 L16/8000
a=rtpmap:98 L16/11025/2
```

MediaDescription.Format is a single string
And there is no test for this case

**Comment by ernado** [comment]
So how should we handle that case?
If I understood correctly, `MediaDescription.Format` would be "96 97 98"
and `Media.Attributes` would contain those 3 attributes like
```
rtpmap: ["96 L8/8000", "97 L16/8000", "98 L16/11025/2"] 
```

**Comment by teeson** [comment]
I think the parser should process the feature specified in rfc4566, so the user need not to re-parse that field.
Advise  `MediaDescription.Format` to be `[]string`
and methods for `a=rtpmap, a=fmtp`  and other predefined attributes to provide a easy use API

**Comment by ernado** [comment]
So `Format` will be `Formats` with ["96", "97", "98"]? It is easy to implement, will do it soon.
Also I will think about methods for such attributes. Thank you for feedback.

**Comment by ernado** [comment]
Should be available in `v0.13.0`, i've added:
https://godoc.org/github.com/gortc/sdp#Media.PayloadFormat and  MediaDescription.Formats`

**Comment by ernado** [comment]
@teeson, I will add more API helpers for attributes when I will work on ICE. 
If you want those faster, feel free to open new issues with API feature request (ideally with wanted method signatures) and I will work on them.
I'm trying to make issues as discrete as possible, it can be not so usable for you, so you can open one meta-issue with the list of requested API features and I will do the micro-management by myself.

I'm currently not using high-level API so I don't know what changes will improve user experience, so I really appreciate your feedback, thank you again. 
Sorry for delay, was working on other sub-projects.

**Comment by teeson** [comment]
@ernado , Sorry to reply you so late. I'm so busy on my main work.
I will make an issue for a list all high level API what we commonly used in products when i have free time these days.
