### ISSUE TITLE
Decode of session ID can fail on 32-bit platforms

### ISSUE THREAD

**Issue by sandykellagher** [gortc/sdp#19]
Hello,

I have run into a problem whereby the SDP decode function fails, due to a session ID that is too big to be stored in a 32-bit integer. The same code runs fine on a 64-bit platform,

My suggestion to fix this would be to change SessionID and SessionVersion to be strings rather than ints, which would be a very simple change but not backwards compatible with existing code that uses the library. The same goes for changing the type to int64.

If you agree, I could submit a PR with necessary changes.

**Comment by ius** [comment]
I've run into the very same issue - ie. it fails for `GOARCH=arm` because the fields may contain millisecond timestamps (> 32 bits).

According to RFC4566 there don't appear to be any bounds, so *string* might be the most appropriate choice..
