### ISSUE TITLE
failed to decode sess-id: strconv.Atoi: parsing "38990265062388": value out of range

### ISSUE THREAD

**Issue by jonas-eschmann** [gortc/sdp#20]
Hi, I am encountering following error, when opening a rtsp stream on a 32bit arm device.

`failed to decode sess-id: strconv.Atoi: parsing "38990265062388": value out of range`
https://github.com/gortc/sdp/blob/0abb7ec4b3492c82e30a97fd9468e80e2511705f/decoder.go#L669

I am not sure if it is a bug or a feature, just wanted to let you know. 
The cause of this seems to be the value exceeding 2^32 (it is approximately 2^45)

Best regards,
Jonas

**Comment by ernado** [comment]
Hey, can you please try `v0.18.0` version?

**Comment by jonas-eschmann** [comment]
Thanks for your reply! You are right, I was using v0.17.0 and v0.18.0 works like a charm. I did not notice it was fixed in https://github.com/gortc/sdp/commit/0abb7ec4b3492c82e30a97fd9468e80e2511705f only a couple days ago

**Comment by jonas-eschmann** [comment]
Thanks for your reply! You are right, I was using v0.17.0 and v0.18.0 works like a charm. I did not notice it was fixed in https://github.com/gortc/sdp/commit/0abb7ec4b3492c82e30a97fd9468e80e2511705f only a couple days ago
