### ISSUE TITLE
Typo in decoding connection data TTL within media section

### ISSUE THREAD

**Issue by sandykellagher** [gortc/sdp#24]
Hello,
There is a typo at line 506 of decoder.go, which affects the decoding of connection data TTL within a media section.

Line 506 currently reads
`m.Connection.TTL, err = decodeByte(first)`

It should read:
`d.m.Connection.TTL, err = decodeByte(first)`

Thanks
Sandy

**Comment by ernado** [comment]
Good catch, fixed in `v0.18.2`
