### ISSUE TITLE
Avoid panic

### ISSUE THREAD

**Issue by backkem** [gortc/sdp#4]
There are quite some uses of the panic keyword, mostly in the default case of switch statements. Is there a reason for this? It seems strange to 'blow up' the program in case of unexpected input. Users of the library would have to recover methods that may panic. In addition, gracefully handling unexpected input seems rather important in a P2P protocol. Maybe we should just return errors in these cases? Finally, It would also make testing easier.

**Comment by ernado** [comment]
Hi @backkem, thank you for the response. Don't worry, no unexpected input should cause the panic. 
I'm using panic to ensure internal consistency in code, putting it in unreachable code branches.
They can be called only as a cause of some nasty and obvious bug that also means that the program is incorrect and output could be incorrect too. The standard library is also using panics in such way.

Do you have an example of input that causes panic?

**Comment by backkem** [comment]
Ah, you are right. Thanks for clarifying.
