### ISSUE TITLE
"Connection" field  in media isn't recognized 

### ISSUE THREAD

**Issue by zombiecong** [gortc/sdp#5]
[sdp file](https://gist.github.com/zombiecong/19d110ea6162dabedba0d03120d818b3)

`c=IN IP4 0.0.0.0` is media field , but it's recognized as "Session Description Connection".

https://tools.ietf.org/html/rfc4566#page-9

**Comment by ernado** [comment]
@zombiecong thank you!
Should be fixed in v0.9.2. Please check if works for you.

**Comment by zombiecong** [comment]
@ernado Yes, it works. Thanks.
